// tests go here; this will not be compiled when this package is used as a library
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(100)
music.stopAllSounds()
basic.forever(function () {
    motorbit.MotorRun(motorbit.Motors.M1, 255)
    motorbit.MotorRun(motorbit.Motors.M2, 255)
    motorbit.MotorRun(motorbit.Motors.M3, 255)
    motorbit.MotorRun(motorbit.Motors.M4, 255)
    basic.pause(1000)
    motorbit.MotorRun(motorbit.Motors.M1, -255)
    motorbit.MotorRun(motorbit.Motors.M2, -255)
    motorbit.MotorRun(motorbit.Motors.M3, -255)
    motorbit.MotorRun(motorbit.Motors.M4, -255)
    basic.pause(1000)
    motorbit.MotorRun(motorbit.Motors.M1, 0)
    motorbit.MotorRun(motorbit.Motors.M2, 0)
    motorbit.MotorRun(motorbit.Motors.M3, 0)
    motorbit.MotorRun(motorbit.Motors.M4, 0)
    basic.pause(1000)
})
